sudo: required
services:
- docker
language: node_js
node_js:
- '7'
install:
- cd ui/frontend
- npm install
- npm run build
- cd ../..
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- docker-compose -f docker-compose.ui.yml -f docker-compose.run.yml up --build -d
- docker build -t battleground/battleground .
- docker run --network=host battleground/battleground python start.py
script: docker run --network=host battleground/battleground pytest unit_tests
after_success:
- chmod +x ./deploy_scripts/*.sh
- chmod 600 deploy_key
- test $TRAVIS_BRANCH = "master" &&
  test $TRAVIS_PULL_REQUEST = "false" &&
  ./deploy_scripts/do_deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in deploy_key.enc -out deploy_key -d
