sudo: required
services:
- docker
language: node_js
node_js:
- '7'
install:
- yarn install
- yarn run build
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- docker-compose -f docker-compose.yml up --build -d
- docker build -t battleground/arenarium_api ./api/
# - docker run --network=host  battleground/arenarium_api python start.py
script: docker run --network=host  battleground/arenarium_api pytest unit_tests
after_success:
- chmod +x ./deploy_scripts/*.sh
- test $TRAVIS_BRANCH = "master" &&
  test $TRAVIS_PULL_REQUEST = "false" &&
  ./deploy_scripts/push_images.sh
