version: '3'

services:
  mongo:
    image: mongo:3.4
    volumes:
      - /data:/data/db
    ports:
      - 27017:27017

  uwsgi:
    image: battleground/uwsgi:latest
    build: ./api
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo:27017

  nginx:
    image: battleground/nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - uwsgi
    ports:
      - 5000:80
