version: '3'

services:
  mongo:
    image: mongo:3.4
    volumes:
      - /data:/data/db
    ports:
      - 27017:27017

  arenarium_api:
    image: battleground/arenarium_api:latest
    build: ./api
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo:27017

  arenarium_web:
    image: battleground/arenarium_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - arenarium_api
    ports:
      - 80:80
